In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
dataset=pd.read_csv('Black Friday Sales Prediction.csv')

In [3]:
dataset.head()

Gender  Age  Occupation  Stay in Years  Marital Status  Prod_category  \
0      F   10          10              2               0              3   
1      F   10          10              2               0              1   
2      F   10          10              2               0             12   
3      F   10          10              2               0             12   
4      M   60          16              5               0              8   

   Category  Purchase  
0         1      8370  
1         1     15200  
2         1      1422  
3         1      1057  
4         0      7969

In [4]:
x=dataset.iloc[:,:7].values
x

array([['F', 10, 10, ..., 0, 3, 1],
       ['F', 10, 10, ..., 0, 1, 1],
       ['F', 10, 10, ..., 0, 12, 1],
       ...,
       ['M', 40, 16, ..., 0, 8, 0],
       ['M', 40, 16, ..., 0, 5, 0],
       ['M', 40, 16, ..., 0, 5, 0]], dtype=object)

In [5]:
y=dataset.iloc[:,7:8].values

In [6]:
y

array([[ 8370],
       [15200],
       [ 1422],
       ...,
       [ 8043],
       [ 7172],
       [ 6875]], dtype=int64)

In [7]:
from sklearn.preprocessing import LabelEncoder
lb=LabelEncoder()

In [8]:
x[:,0]=lb.fit_transform(x[:,0])

In [9]:
x

array([[0, 10, 10, ..., 0, 3, 1],
       [0, 10, 10, ..., 0, 1, 1],
       [0, 10, 10, ..., 0, 12, 1],
       ...,
       [1, 40, 16, ..., 0, 8, 0],
       [1, 40, 16, ..., 0, 5, 0],
       [1, 40, 16, ..., 0, 5, 0]], dtype=object)

In [10]:
from sklearn.tree import DecisionTreeRegressor
regressor = DecisionTreeRegressor(random_state=0)
regressor.fit(x,y)


DecisionTreeRegressor(criterion='mse', max_depth=None, max_features=None,
           max_leaf_nodes=None, min_impurity_decrease=0.0,
           min_impurity_split=None, min_samples_leaf=1,
           min_samples_split=2, min_weight_fraction_leaf=0.0,
           presort=False, random_state=0, splitter='best')

In [11]:
y_p = regressor.predict([[0,10,10,2,1,4,1]])

In [12]:
y_p

array([2757.])